version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: dwh
      POSTGRES_PASSWORD: dwhpassword
      POSTGRES_DB: dwh
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'

volumes:
  db-data:
